AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CustomSkill:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: skill/dist/
      Handler: index.handler
      Runtime: nodejs8.10
    Events:
      HelloWorld:
        Type: AlexaSkill